/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

/**
 *
 * @author User
 */
public class frameApp extends javax.swing.JFrame {
;
    /**
     * Creates new form frameApp
     */
    public frameApp() {
        initComponents();
        customInit();
        setLocationRelativeTo(null);
        setTitle("Aplikasi Perhitungan Hari");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSkala = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        spnTahun = new javax.swing.JSpinner();
        cmbBulan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblKabisat = new javax.swing.JLabel();
        btnHitungSelisih = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblHasilSelisih = new javax.swing.JLabel();
        lblVariasi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dateSelesai = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateMulai = new com.toedter.calendar.JDateChooser();
        btnHitung = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("APLIKASI PERHITUNGAN HARI");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnTahun.setModel(new javax.swing.SpinnerNumberModel(2025, 1900, 2100, 1));
        spnTahun.setEditor(new javax.swing.JSpinner.NumberEditor(spnTahun, "#"));
        jPanel1.add(spnTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 300, -1));

        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 300, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Bulan ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        lblKabisat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblKabisat.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblKabisat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 360, 30));

        btnHitungSelisih.setText("HITUNG SELISIH");
        btnHitungSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungSelisihActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitungSelisih, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tahun");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        lblHasilSelisih.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblHasilSelisih.setForeground(new java.awt.Color(0, 0, 0));
        lblHasilSelisih.setText("Selisih:-");
        jPanel1.add(lblHasilSelisih, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 150, 30));

        lblVariasi.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblVariasi.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblVariasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 360, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 640, 10));
        jPanel1.add(dateSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 300, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tanggal Selesai");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 161, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("--- Hitung Selisih Hari ---");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 220, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tanggal Mulai");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 161, -1));
        jPanel1.add(dateMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 300, -1));

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblHasil.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblHasil.setForeground(new java.awt.Color(0, 0, 0));
        lblHasil.setText("Jumlah Hari:-");
        jPanel1.add(lblHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, 30));

        btnReset.setText("RESET ALL");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        Content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 680, 430));

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customInit() {
    // 1. Mengisi JComboBox (cmbBulan) dengan nama-nama bulan
    cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
        "Januari", "Februari", "Maret", "April", "Mei", "Juni", 
        "Juli", "Agustus", "September", "Oktober", "November", "Desember" 
    }));

    // 2. Mengatur JSpinner (spnTahun)
    // Ambil tahun saat ini sebagai nilai default
    int currentYear = java.time.Year.now().getValue();
    
    // Set model spinner: (nilai_default, min, max, langkah)
    spnTahun.setModel(new javax.swing.SpinnerNumberModel(currentYear, 1900, 2100, 1));
    
    // Baris ini penting agar format tahun tidak memakai koma (misal: 2,025)
    spnTahun.setEditor(new javax.swing.JSpinner.NumberEditor(spnTahun, "#"));
}
    
    private void btnHitungSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungSelisihActionPerformed
        try {
               // 1. Ambil tanggal dari JDateChooser
               java.util.Date tglMulaiUtil = dateMulai.getDate();
               java.util.Date tglSelesaiUtil = dateSelesai.getDate();

               // 2. Cek apakah pengguna sudah memilih tanggal
               if (tglMulaiUtil == null || tglSelesaiUtil == null) {
                   lblHasilSelisih.setText("Error: Harap pilih kedua tanggal.");
                   return;
               }

               // 3. Konversi dari java.util.Date ke java.time.LocalDate (API modern)
               java.time.LocalDate tglMulai = tglMulaiUtil.toInstant()
                       .atZone(java.time.ZoneId.systemDefault())
                       .toLocalDate();

               java.time.LocalDate tglSelesai = tglSelesaiUtil.toInstant()
                       .atZone(java.time.ZoneId.systemDefault())
                       .toLocalDate();

               // 4. Hitung selisih hari menggunakan ChronoUnit
               long selisihHari = java.time.temporal.ChronoUnit.DAYS.between(tglMulai, tglSelesai);

               // 5. Tampilkan hasil
               lblHasilSelisih.setText("Selisih: " + selisihHari + " hari.");

           } catch (Exception e) {
               lblHasilSelisih.setText("Error: Gagal menghitung.");
           }
    }//GEN-LAST:event_btnHitungSelisihActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            // 1. Ambil input dari GUI
            int monthIndex = cmbBulan.getSelectedIndex(); 
            int month = monthIndex + 1; // LocalDate menggunakan bulan 1-12
            int year = (Integer) spnTahun.getValue();

            // 2. Logika Program
            java.time.LocalDate firstDayOfMonth = java.time.LocalDate.of(year, month, 1);

            // Menghitung jumlah hari (otomatis menangani kabisat)
            int lengthOfMonth = firstDayOfMonth.lengthOfMonth();

            // === TAMBAHAN UNTUK MENAMPILKAN STATUS KABISAT ===
            // Kita gunakan method isLeap() dari java.time.Year
            boolean isKabisat = java.time.Year.isLeap(year);
            if (isKabisat) {
                lblKabisat.setText("Tahun " + year + " adalah TAHUN KABISAT.");
            } else {
                lblKabisat.setText("Tahun " + year + " BUKAN tahun kabisat.");
            }
            // =================================================

            // 3. Tampilkan hasil utama
            lblHasil.setText("Jumlah Hari: " + lengthOfMonth);

            // 4. Logika untuk Variasi
            java.time.DayOfWeek firstDayName = firstDayOfMonth.getDayOfWeek();
            java.time.LocalDate lastDayOfMonth = firstDayOfMonth.withDayOfMonth(lengthOfMonth);
            java.time.DayOfWeek lastDayName = lastDayOfMonth.getDayOfWeek();

            java.util.Locale indonesianLocale = new java.util.Locale("id", "ID");
            String firstDayStr = firstDayName.getDisplayName(java.time.format.TextStyle.FULL, indonesianLocale);
            String lastDayStr = lastDayName.getDisplayName(java.time.format.TextStyle.FULL, indonesianLocale);

            lblVariasi.setText("Hari pertama: " + firstDayStr + " | Hari terakhir: " + lastDayStr);

        } catch (Exception e) {
            lblHasil.setText("Error: Input tidak valid.");
            lblVariasi.setText("-");
            lblKabisat.setText("-"); // Jangan lupa reset label kabisat jika error
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // --- 1. Reset Bagian Perhitungan Hari ---
        // Set ComboBox kembali ke item pertama (Januari)
        cmbBulan.setSelectedIndex(0);

        // Set Spinner kembali ke tahun saat ini
        int currentYear = java.time.Year.now().getValue();
        spnTahun.setValue(currentYear);

        // Bersihkan semua label hasil
        lblHasil.setText("Jumlah Hari: -");
        lblVariasi.setText("-");
        lblKabisat.setText("-"); // Label dari langkah sebelumnya

        // --- 2. Reset Bagian Selisih Hari ---

        // Kosongkan pilihan tanggal
        dateMulai.setDate(null);
        dateSelesai.setDate(null);

        // Bersihkan label hasil selisih
        lblHasilSelisih.setText("Selisih: -");
    }//GEN-LAST:event_btnResetActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.ButtonGroup bgSkala;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitungSelisih;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbBulan;
    private com.toedter.calendar.JDateChooser dateMulai;
    private com.toedter.calendar.JDateChooser dateSelesai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblHasilSelisih;
    private javax.swing.JLabel lblKabisat;
    private javax.swing.JLabel lblVariasi;
    private javax.swing.JSpinner spnTahun;
    // End of variables declaration//GEN-END:variables

    private void setupInitialValues() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
